name: Continuous deployment (backend)

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install and test backend
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Lint backend
        working-directory: ./backend
        run: npm run lint

      - name: Run backend tests
        working-directory: ./backend
        run: npm run test

      # Modify for deployment
      - name: Modify package.json
        working-directory: ./backend
        run: jq '.imports["#*"] = "./dist/*"' package.json > temp.temp.json && mv temp.temp.json package.json

      - name: Updating Ubuntu system and Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      # Heroku deployment
      - name: Login to Heroku container registry
        working-directory: ./backend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Push to Heroku
        working-directory: ./backend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web

      - name: Deploy to Heroku
        working-directory: ./backend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
